### ISSUE TITLE
X-as (azimuth) haaks?

### ISSUE THREAD

**Issue by Deadlykeyboard** [Deadlykeyboard/SmartSun#4]
Wij hebben wel gecorrigeerd voor de y-as maar nu vraag ik mij af, staat de x-as wel haaks op de zon?

**Comment by Tommie1236** [comment]
denk niet dat dit een antwoord is maar snap ook niet helemaal wat je bedoelt

dat hangt er vanaf hoe je met je coords werkt. je kan altijd een haakse lijn (y) van een punt (zon) naar een lijn (x) maken. de y is geflipt omdat de stepper een andere origin en direction had dan de zon. dat kan ook voor x zo gedaan worden als dat moet.
